### ISSUE TITLE
Avoid duplicates in PNGs

### ISSUE THREAD

**Issue by kelson42** [kiwix/phet#11]
Each localized version of an experiment use the same PNG content, but in the ZIM, each localized experiment has its own copy of these PNG files.

For example:```

$ ls -la forces-and-motion-basics_*_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_be_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_bs_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_cs_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_da_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_de_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_el_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_en_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_es_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_es_PE_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_et_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_fr_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_hu_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_in_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_it_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_nl_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_pt_BR_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_si_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_sk_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_vi_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_zh_CN_27.png
-rw-r--r-- 1 kelson wikidev 338 Jan 16 19:53 forces-and-motion-basics_zh_TW_27.png
```

This generates artifically long creation process and a far too big files (if many languages).

I recommend to use only the same file.

**Comment by ISNIT0** [comment]
Still some creation optimisations, but the quick fix was to just re-write to the same file based on MD5 hash

**Comment by kelson42** [comment]
Works fine, for all language the file still make around 150MB. What kind of optims do you still want to implement?
