### ISSUE TITLE
Single language ZIMs do not provide access to simulation

### ISSUE THREAD

**Issue by kelson42** [kiwix/phet#24]
Tested with IT and FR, the welcome page does not provide any activity thumbnails... whereas the version with all languages seems to work fine

**Comment by ISNIT0** [comment]
Its because your local storage is saving the incorrect language, this I'd a bug I need to fix, but not a problem in production.

**Comment by ISNIT0** [comment]
So you need to run localStorage.clear() in your browser then refresh

**Comment by kelson42** [comment]
@ISNIT0 I do not really understant why this is not a problem in Production?

**Comment by ISNIT0** [comment]
Sorry, I was thinking of the app. It's still a problem on kiwix-serve

**Comment by kelson42** [comment]
@ISNIT0 OK, probably a random prefix should be added to the js to avoid collisions in the storage variables names.

**Comment by kelson42** [comment]
@ISNIT0 works now :) THX
