### ISSUE TITLE
Sanitize HTML title 

### ISSUE THREAD

**Issue by kelson42** [kiwix/phet#3]
HTML titles contain characters which impair ZIM search by title. For example a title node looks like following:

`<title>&#8234;Balloons and Static Electricity&#8236; 1.1.3</title>`

I'm not sure about which character is represented by "&#8234;" and "&#8236;", but this would be helpful if They could be removed. We could for example have:

`<titleBalloons and Static Electricity - 1.1.3</title>`

**Comment by ISNIT0** [comment]
As discussed with @kelson42 offline, the special characters turn out to be LTR/RTL directional notation, so they should be left in.

Closing this issue :)

**Comment by kelson42** [comment]
These characters are now removed in zimwriterfs at the time of the ZIM creation.
