### ISSUE TITLE
Best contact for discussion with PhET team?

### ISSUE THREAD

**Issue by ariel-phet** [kiwix/phet#8]
Hello,

I am the Director of Development for the PhET interactive simulations project, who would be the best contact at your organization to have a discussion about the app you have up on Google play?

Thanks!

**Comment by kelson42** [comment]
Dear Ariel. Thank you for taking contact. Stéphane, a colleague of mine, has just sent you an invitation on LinkedIn so you later can have a phonecall.

**Comment by ariel-phet** [comment]
Excellent, thank you! I have accepted his invitation and written him back on LinkedIn.

**Comment by kelson42** [comment]
@ariel-phet Ok, I close this ticket then :)
